/* 
 * File:   ADC_CONFIG.h
 * Author: ibrah
 *
 * Created on March 25, 2025, 5:09 PM
 */

#ifndef ADC_CONFIG_H
#define	ADC_CONFIG_H

/***********SECTION: library includes*******************/
#include "ADC_private.h"
#include "../INTERRUPT/INTERNAL_INTERRUPT/INTERNAL_INTERRUPT.h"

/***********SECTION: macro definition*******************/

/*
 *ADC_RUN_TIME_CONFIG //if you have multiple ADC or you want to change some config in run time
 * ADC_PRE_BUILD_CONFIG //set config in this file directly but won't be able to change configuration in run time
 */
#define ADC_CODE_CONFIG ADC_PRE_BUILD_CONFIG 


/*
 *ADC_CONVERSION_BY_BLOCKING
 *ADC_CONVERSION_BY_INTERRUPT
 */
#define ADC_CONVERSION_METHOD ADC_CONVERSION_BY_INTERRUPT

#if ADC_CODE_CONFIG==ADC_PRE_BUILD_CONFIG 
/**
    _ADC_CONVERSION_CLOCK_FOSC_2
    _ADC_CONVERSION_CLOCK_FOSC_8
    _ADC_CONVERSION_CLOCK_FOSC_32
    _ADC_CONVERSION_CLOCK_FRC
    _ADC_CONVERSION_CLOCK_FOSC_4
    _ADC_CONVERSION_CLOCK_FOSC_16
    _ADC_CONVERSION_CLOCK_FOSC_64
*/
#define ADC_CONVERSION_CLOCK _ADC_CONVERSION_CLOCK_FOSC_16
/*
    _ADC_ACQUSITION_TIME_0TAD
    _ADC_ACQUSITION_TIME_2TAD
    _ADC_ACQUSITION_TIME_4TAD
    _ADC_ACQUSITION_TIME_6TAD
    _ADC_ACQUSITION_TIME_8TAD
    _ADC_ACQUSITION_TIME_12TAD
    _ADC_ACQUSITION_TIME_16TAD
    _ADC_ACQUSITION_TIME_20TAD
 */
#define ADC_ACQUISTION_TIME _ADC_ACQUSITION_TIME_12TAD

/*
 _ADC_PINS_ALL_DIGITAL_FUNCTIONALLITY
 _ADC_AN0_ANALOG_FUNCTIONALLITY
 _ADC_AN1_ANALOG_FUNCTIONALLITY
 _ADC_AN2_ANALOG_FUNCTIONALLITY
 _ADC_AN3_ANALOG_FUNCTIONALLITY
 _ADC_AN4_ANALOG_FUNCTIONALLITY
 _ADC_AN5_ANALOG_FUNCTIONALLITY
 _ADC_AN6_ANALOG_FUNCTIONALLITY
 _ADC_AN7_ANALOG_FUNCTIONALLITY
 _ADC_AN8_ANALOG_FUNCTIONALLITY
 _ADC_AN9_ANALOG_FUNCTIONALLITY
 _ADC_AN10_ANALOG_FUNCTIONALLITY
 _ADC_AN11_ANALOG_FUNCTIONALLITY
 _ADC_AN12_ANALOG_FUNCTIONALLITY
 */

#define ADC_ANALOG_DIGITAL_FUNCTIONLLITY    _ADC_AN3_ANALOG_FUNCTIONALLITY

/*
 _ADC_RESULT_RIGHT_JUSTIFIED
 _ADC_RESULT_LEFT_JUSTIFIED
 */
#define ADC_RESULT_JUSTIFICATION _ADC_RESULT_RIGHT_JUSTIFIED


/*
 _ADC_INTERNAL_VOLTAGE_REF 
 _ADC_EXTERNAL_VOLTAGE_REF
 */
#define ADC_VOLTAFE_REF  _ADC_INTERNAL_VOLTAGE_REF 

#if INTERRUPT_PRIORITY_FEATURE==INTERRUPT_FEATURE_ENABLE
/*
 _ADC_HIGH_PRIORITY
 _ADC_LOW_PRIORITY 
 */
#define ADC_PRIORITY_INTERRUPT _ADC_HIGH_PRIORITY
#endif 


#endif
/***********SECTION: function like macro*******************/


/***********SECTION: data type definition*******************/

/***********SECTION: function decleration*******************/

#endif	/* ADC_CONFIG_H */

